### ISSUE TITLE
Publish NPM package

### ISSUE THREAD

**Issue by lulunac27a** [mulhoon/score.js#6]
I would like to use this project in a Node.js package with version tracking like changes in new version and a feature to save user data permanently to local project.

**Comment by mulhoon** [comment]
You can find it here: https://www.npmjs.com/package/score-js
Is that what you need?

**Comment by lulunac27a** [comment]
The NPM package needs a new version because this package made some changes since the last version released.

**Comment by lulunac27a** [comment]
Please update the new version for the NPM package to v0.1.0.

**Comment by lulunac27a** [comment]
The [NPM website](https://www.npmjs.com/package/score-js) shows the old version, not the new version. To update the NPM website with the new version please run the `npm login` and `npm publish` commands in the command line.

**Comment by mulhoon** [comment]
Thanks @lulunac27a - I've had to update it to [@mulhoon/score.js](https://www.npmjs.com/package/@mulhoon/score.js) hope this helps.

**Comment by lulunac27a** [comment]
The NPM package website for this package has been updated to the latest version.
